-- todo: make seperate versions for rep and rep+
-- I believe Isaac Boss and Corpse theme are different, that's it

---@type TempoDefs
local tempoDefs = {
    [Music.MUSIC_BASEMENT]                      = {bpm = 140},
    [Music.MUSIC_CAVES]                         = {bpm = 120, bpms = {[3853] = 131.578, [4309] = 120}, offset = 83},
    [Music.MUSIC_DEPTHS]                        = {bpm = 95},
    [Music.MUSIC_CELLAR]                        = {bpm = 140, offset = 64},
    [Music.MUSIC_CATACOMBS]                     = {bpm = 120, offset = 50},
    [Music.MUSIC_NECROPOLIS]                    = {bpm = 120},
    [Music.MUSIC_WOMB_UTERO]                    = {bpm = 90},
    [Music.MUSIC_GAME_OVER]                     = {bpm = 85, timeSig = 3},
    [Music.MUSIC_BOSS]                          = {bpm = 150, timeSigs = {[2] = 4}},
    [Music.MUSIC_CATHEDRAL]                     = {bpm = 100},
    [Music.MUSIC_SHEOL]                         = {bpm = 110, offset = 269},
    [Music.MUSIC_DARK_ROOM]                     = {bpm = 90, offset = 82},
    [Music.MUSIC_CHEST]                         = {bpm = 110, offset = 3},
    [Music.MUSIC_BURNING_BASEMENT]              = {bpm = 140, timeSigs = {[2] = 4}},
    [Music.MUSIC_FLOODED_CAVES]                 = {bpm = 120, offset = 100},
    [Music.MUSIC_DANK_DEPTHS]                   = {bpm = 95},
    [Music.MUSIC_SCARRED_WOMB]                  = {bpm = 90},
    [Music.MUSIC_BLUE_WOMB]                     = {bpm = 80},
    [Music.MUSIC_UTERO]                         = {bpm = 90},
    [Music.MUSIC_MOM_BOSS]                      = {bpm = 160, timeSigs = {[3] = 4}},
    [Music.MUSIC_MOMS_HEART_BOSS]               = {bpm = 160},
    [Music.MUSIC_ISAAC_BOSS]                    = {bpm = 120, offset = 30},
    [Music.MUSIC_SATAN_BOSS]                    = {bpm = 165, timeSigs = {[2] = 4}, offset = 31},
    [Music.MUSIC_DARKROOM_BOSS]                 = {bpm = 170, offset = 205},
    [Music.MUSIC_BLUEBABY_BOSS]                 = {bpm = 110, timeSigs = {[2] = 4}},
    [Music.MUSIC_BOSS2]                         = {bpm = 150, offset = 26},
    [Music.MUSIC_HUSH_BOSS]                     = {bpm = 160, offset = 375},
    [Music.MUSIC_ULTRAGREED_BOSS]               = {bpm = 165, offset = 109},
    [Music.MUSIC_LIBRARY_ROOM]                  = {bpm = 110, bpms = {[3881] = 124.224, [4364] = 110}, offset = 57},
    [Music.MUSIC_SECRET_ROOM]                   = {bpm = 120, timeSig = 3},
    [Music.MUSIC_SECRET_ROOM2]                  = {bpm = 120, timeSig = 3},
    [Music.MUSIC_DEVIL_ROOM]                    = {}, -- arrhythmic
    [Music.MUSIC_ANGEL_ROOM]                    = {bpm = 100},
    [Music.MUSIC_SHOP_ROOM]                     = {bpm = 80, bpms = {[7580] = 89.418, [8250] = 80}, offset = 81},
    [Music.MUSIC_ARCADE_ROOM]                   = {bpm = 130},
    [Music.MUSIC_BOSS_OVER]                     = {bpm = 85, timeSig = 3},
    [Music.MUSIC_CHALLENGE_FIGHT]               = {bpm = 150, offset = -93},
    [Music.MUSIC_BOSS_RUSH]                     = {bpm = 180, timeSig = 7},
    [Music.MUSIC_JINGLE_BOSS_RUSH_OUTRO]        = {},
    [Music.MUSIC_BOSS3]                         = {bpm = 160},
    [Music.MUSIC_JINGLE_BOSS_OVER3]             = {},
    [Music.MUSIC_MOTHER_BOSS]                   = {bpm = 130, triplet = true},
    [Music.MUSIC_DOGMA_BOSS]                    = {bpm = 180},
    [Music.MUSIC_BEAST_BOSS]                    = {bpm = 160, timeSig = 6},
    [Music.MUSIC_JINGLE_MOTHER_OVER]            = {},
    [Music.MUSIC_JINGLE_DOGMA_OVER]             = {},
    [Music.MUSIC_JINGLE_BEAST_OVER]             = {},
    [Music.MUSIC_PLANETARIUM]                   = {bpm = 120},
    [Music.MUSIC_SECRET_ROOM_ALT_ALT]           = {bpm = 120, offset = 49},
    [Music.MUSIC_BOSS_OVER_TWISTED]             = {bpm = 85, timeSig = 3},
    [Music.MUSIC_CREDITS]                       = {},
    [Music.MUSIC_TITLE]                         = {},
    [Music.MUSIC_TITLE_AFTERBIRTH]              = {},
    [Music.MUSIC_TITLE_REPENTANCE]              = {},
    [Music.MUSIC_JINGLE_GAME_START_ALT]         = {},
    [Music.MUSIC_JINGLE_NIGHTMARE_ALT]          = {},
    [Music.MUSIC_MOTHERS_SHADOW_INTRO]          = {},
    [Music.MUSIC_DOGMA_INTRO]                   = {},
    [Music.MUSIC_STRANGE_DOOR_JINGLE]           = {},
    [Music.MUSIC_DARK_CLOSET]                   = {},
    [Music.MUSIC_CREDITS_ALT]                   = {},
    [Music.MUSIC_CREDITS_ALT_FINAL]             = {},
    [Music.MUSIC_JINGLE_BOSS]                   = {},
    [Music.MUSIC_JINGLE_BOSS_OVER]              = {},
    [Music.MUSIC_JINGLE_HOLYROOM_FIND]          = {},
    [Music.MUSIC_JINGLE_SECRETROOM_FIND]        = {},
    [Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_0]   = {},
    [Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_1]   = {},
    [Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_2]   = {},
    [Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_3]   = {},
    [Music.MUSIC_JINGLE_CHALLENGE_ENTRY]        = {},
    [Music.MUSIC_JINGLE_CHALLENGE_OUTRO]        = {},
    [Music.MUSIC_JINGLE_GAME_OVER]              = {},
    [Music.MUSIC_JINGLE_DEVILROOM_FIND]         = {},
    [Music.MUSIC_JINGLE_GAME_START]             = {},
    [Music.MUSIC_JINGLE_NIGHTMARE]              = {},
    [Music.MUSIC_JINGLE_BOSS_OVER2]             = {},
    [Music.MUSIC_JINGLE_HUSH_OVER]              = {},
    [Music.MUSIC_INTRO_VOICEOVER]               = {},
    [Music.MUSIC_EPILOGUE_VOICEOVER]            = {},
    [Music.MUSIC_VOID]                          = {bpm = 110},
    [Music.MUSIC_VOID_BOSS]                     = {bpm = 180, length = 106667, triplets = {[0] = false, [288] = true}},
    [Music.MUSIC_DOWNPOUR]                      = {bpm = 144},
    [Music.MUSIC_MINES]                         = {bpm = 136},
    [Music.MUSIC_MAUSOLEUM]                     = {bpm = 119},
    [Music.MUSIC_CORPSE]                        = {bpm = 110, bpms = {[104181] = 128.755}, length = 104647},
    [Music.MUSIC_DROSS]                         = {bpm = 120, offset = 237},
    [Music.MUSIC_ASHPIT]                        = {bpm = 106, timeSigs = {[3] = 4}},
    [Music.MUSIC_GEHENNA]                       = {bpm = 110},
    [Music.MUSIC_ISAACS_HOUSE]                  = {bpm = 90, timeSig = 3},
    [Music.MUSIC_FINAL_VOICEOVER]               = {},
    [Music.MUSIC_DOWNPOUR_REVERSE]              = {bpm = 144},
    [Music.MUSIC_DROSS_REVERSE]                 = {bpm = 120},
    [Music.MUSIC_MINESHAFT_AMBIENT]             = {},
    [Music.MUSIC_MINESHAFT_ESCAPE]              = {bpm = 120},
    [Music.MUSIC_REVERSE_GENESIS]               = {bpm = 130, timeSig = 3}
}

local MUSIC_DEATHMATCH = Music.MUSIC_DEATHMATCH or Isaac.GetMusicIdByName("Deathmatch")
if MUSIC_DEATHMATCH then
    tempoDefs[MUSIC_DEATHMATCH]                 = {name = "There Can Be Only One"}
end


---@type table<Music, string>
local names = {
    [Music.MUSIC_BASEMENT]                      = "Diptera Sonata",
    [Music.MUSIC_CAVES]                         = "Sodden Hollow (Caves)",
    [Music.MUSIC_DEPTHS]                        = "Abyss (The Depths)",
    [Music.MUSIC_CELLAR]                        = "Periculum (The Cellar)",
    [Music.MUSIC_CATACOMBS]                     = "Capiticus Calvaria (Catacombs)",
    [Music.MUSIC_NECROPOLIS]                    = "When Blood Dries (Necropolis)",
    [Music.MUSIC_WOMB_UTERO]                    = "Viscera (Womb)",
    [Music.MUSIC_GAME_OVER]                     = "Acceptance (You Died)",
    [Music.MUSIC_BOSS]                          = "Crusade (Basic Boss Fight)",
    [Music.MUSIC_CATHEDRAL]                     = "Everlasting Hymn (Cathedral)",
    [Music.MUSIC_SHEOL]                         = "Duress (Sheol)",
    [Music.MUSIC_DARK_ROOM]                     = "Devoid (Dark Room)",
    [Music.MUSIC_CHEST]                         = "Sketches of Pain (Chest Room)",
    [Music.MUSIC_BURNING_BASEMENT]              = "Fundamentum (Burning Basement)",
    [Music.MUSIC_FLOODED_CAVES]                 = "Kave Diluvii (Flooded Caves)",
    [Music.MUSIC_DANK_DEPTHS]                   = "Pulso Profundum (Dank Depths)",
    [Music.MUSIC_SCARRED_WOMB]                  = "Cicatrix (Scarred Womb)",
    [Music.MUSIC_BLUE_WOMB]                     = "Nativitate (Dead Womb)",
    [Music.MUSIC_UTERO]                         = "Caesarian (Utero)",
    [Music.MUSIC_MOM_BOSS]                      = "Matricide (Mom Fight)",
    [Music.MUSIC_MOMS_HEART_BOSS]               = "Ventricide (Womb Fight)",
    [Music.MUSIC_ISAAC_BOSS]                    = "Infanticide (Isaac Fight)",
    [Music.MUSIC_SATAN_BOSS]                    = "Hericide (Satan Fight)",
    [Music.MUSIC_DARKROOM_BOSS]                 = "The Fallen Angel (Dark Room Fight)",
    [Music.MUSIC_BLUEBABY_BOSS]                 = "Ascension (Chest Fight)",
    [Music.MUSIC_BOSS2]                         = "Cerebrum Dispersio (Boss Alt)",
    [Music.MUSIC_HUSH_BOSS]                     = "Morituros (Hush Fight)",
    [Music.MUSIC_ULTRAGREED_BOSS]               = "Chorus Mortis (Ultra Greed)",
    [Music.MUSIC_LIBRARY_ROOM]                  = "Tome of Knowledge (Library)",
    [Music.MUSIC_SECRET_ROOM]                   = "The Forgotten (Secret Room)",
    [Music.MUSIC_SECRET_ROOM2]                  = "Super Secret Room",
    [Music.MUSIC_DEVIL_ROOM]                    = "Anima Vendit (Deal With the Devil)", 
    [Music.MUSIC_ANGEL_ROOM]                    = "Empty Vessels (Angel Room)",
    [Music.MUSIC_SHOP_ROOM]                     = "Murmur of the Harvestman (Store)",
    [Music.MUSIC_ARCADE_ROOM]                   = "Genesis 13:37 (Retro Beats)",
    [Music.MUSIC_BOSS_OVER]                     = "The Calm",
    [Music.MUSIC_CHALLENGE_FIGHT]               = "Ambush",
    [Music.MUSIC_BOSS_RUSH]                     = "Armageddon (Boss Rush)",
    [Music.MUSIC_BOSS3]                         = "Juggernaut (Boss Alt)",
    [Music.MUSIC_MOTHER_BOSS]                   = "Morticide (Corpse Fight)",
    [Music.MUSIC_DOGMA_BOSS]                    = "Living in the Light",
    [Music.MUSIC_BEAST_BOSS]                    = "Revelations 13-1",
    [Music.MUSIC_PLANETARIUM]                   = "Stargazer (Planetarium)",
    [Music.MUSIC_SECRET_ROOM_ALT_ALT]           = "Bygone",
    [Music.MUSIC_BOSS_OVER_TWISTED]             = "Dread (The Calm Twisted)",
    [Music.MUSIC_CREDITS]                       = "Tribute (Credits Roll)",
    [Music.MUSIC_TITLE]                         = "Genesis 22:10 (Title)",
    [Music.MUSIC_TITLE_AFTERBIRTH]              = "Regenesis (Title)",
    [Music.MUSIC_TITLE_REPENTANCE]              = "Genesis Retake Light",
    [Music.MUSIC_CREDITS_ALT]                   = "Hush (Jesus Loves Uke)",
    [Music.MUSIC_VOID]                          = "Terminus",
    [Music.MUSIC_VOID_BOSS]                     = "Delirium",
    [Music.MUSIC_DOWNPOUR]                      = "River of Despair (Downpour)",
    [Music.MUSIC_MINES]                         = "Fissure (Mines)",
    [Music.MUSIC_MAUSOLEUM]                     = "Walls of Denial (Mausoleum)",
    [Music.MUSIC_CORPSE]                        = "Carrion (Corpse)",
    [Music.MUSIC_DROSS]                         = "Night Soil (Dross)",
    [Music.MUSIC_ASHPIT]                        = "Absentia (Ashpit)",
    [Music.MUSIC_GEHENNA]                       = "Morning Star (Gehenna)",
    [Music.MUSIC_ISAACS_HOUSE]                  = "Home"
}

CatGuy:ApplyNameArtistToTempoDefs(tempoDefs, names, "Ridiculon")

tempoDefs[Music.MUSIC_MORTIS]                   = tempoDefs[Music.MUSIC_WOMB_UTERO]

return tempoDefs