---@type table<Music, TempoDef>
local tempoDefs = {
    [Music.MUSIC_BASEMENT]                      = {bpm = 120, offset=192},
    [Music.MUSIC_CAVES]                         = {bpm = 130, offset=171},
    [Music.MUSIC_DEPTHS]                        = {bpm = 90, offset=124},
    [Music.MUSIC_CELLAR]                        = {bpm = 160, offset=184},
    [Music.MUSIC_CATACOMBS]                     = {bpm = 120, offset=136},
    [Music.MUSIC_NECROPOLIS]                    = {bpm = 126, offset=165},
    [Music.MUSIC_WOMB_UTERO]                    = {bpm = 140, offset=114},
    [Music.MUSIC_GAME_OVER]                     = {bpm = 120},
    [Music.MUSIC_BOSS]                          = {bpm = 140, triplet=true, timeSigs={[2]=4}},
    [Music.MUSIC_CATHEDRAL]                     = {bpm = 90},
    [Music.MUSIC_SHEOL]                         = {bpm = 92, timeSigs={[1]=4}},
    [Music.MUSIC_DARK_ROOM]                     = {bpm = 140, offset=19},
    [Music.MUSIC_CHEST]                         = {bpm = 142, offset=241, triplets={[2]=true, [4]=false}},
    [Music.MUSIC_BURNING_BASEMENT]              = {bpm = 130, offset=731, timeSig=3},
    [Music.MUSIC_FLOODED_CAVES]                 = {bpm = 133, timeSig=3},
    [Music.MUSIC_DANK_DEPTHS]                   = {bpm = 89, offset=315},
    [Music.MUSIC_SCARRED_WOMB]                  = {bpm = 100, timeSigs={[2]=4}},
    [Music.MUSIC_BLUE_WOMB]                     = {bpm = 75, offset=317},
    [Music.MUSIC_UTERO]                         = {bpm = 140, offset=107},
    ----[Music.MUSIC_MOM_BOSS]                      = {bpm = 151},
    ----[Music.MUSIC_MOMS_HEART_BOSS]               = {bpm = 0},
    ----[Music.MUSIC_ISAAC_BOSS]                    = {bpm = 0},
    [Music.MUSIC_SATAN_BOSS]                    = {bpm = 100, triplet=true},
    ----[Music.MUSIC_DARKROOM_BOSS]                 = {bpm = 0},
    ----[Music.MUSIC_BLUEBABY_BOSS]                 = {bpm = 0},
    [Music.MUSIC_BOSS2]                         = {bpm = 140, intro=2795, length=118400, timeSigs={[0]=7,[7]=6,[79]=7,[107]=6,[251]=7,[279]=6}},
    [Music.MUSIC_HUSH_BOSS]                     = {bpm = 169, intro=6391, length=177515, timeSigs={[2]=4,[18]=7,[46]=4,[138]=7,[166]=8,[174]=7,[202]=4,[394]=7,[422]=4}},
    ----[Music.MUSIC_ULTRAGREED_BOSS]               = {bpm = 0},
    [Music.MUSIC_LIBRARY_ROOM]                  = {bpm = 110, offset=7, intro=78, length=104704, bpms={[104189]=101.180}},
    [Music.MUSIC_SECRET_ROOM]                   = {bpm = 130, offset=78},
    [Music.MUSIC_SECRET_ROOM2]                  = {bpm = 130},
    [Music.MUSIC_DEVIL_ROOM]                    = {bpm = 30, length=125393, bpms={[112000]=35.84}},
    [Music.MUSIC_ANGEL_ROOM]                    = {bpm = 89, timeSigs={[2]=4}},
    [Music.MUSIC_SHOP_ROOM]                     = {bpm = 90, offset=212},
    [Music.MUSIC_ARCADE_ROOM]                   = {bpm = 120},
    [Music.MUSIC_BOSS_OVER]                     = {bpm = 60, offset=500, intro=4500, length=142000, timeSigs={[4]=4}},
    [Music.MUSIC_CHALLENGE_FIGHT]               = {bpm = 138, triplet=true},
    --[Music.MUSIC_BOSS_RUSH]                     = {bpm = 0},
    ----[Music.MUSIC_JINGLE_BOSS_RUSH_OUTRO]        = {bpm = 0},
    --[Music.MUSIC_BOSS3]                         = {bpm = 0},
    ----[Music.MUSIC_JINGLE_BOSS_OVER3]             = {bpm = 0},
    ----[Music.MUSIC_MOTHER_BOSS]                   = {bpm = 0},
    --[Music.MUSIC_DOGMA_BOSS]                    = {bpm = 0},
    --[Music.MUSIC_BEAST_BOSS]                    = {bpm = 0},
    ----[Music.MUSIC_JINGLE_MOTHER_OVER]            = {bpm = 0},
    ----[Music.MUSIC_JINGLE_DOGMA_OVER]             = {bpm = 0},
    ----[Music.MUSIC_JINGLE_BEAST_OVER]             = {bpm = 0},
    --[Music.MUSIC_PLANETARIUM]                   = {bpm = 0},
    --[Music.MUSIC_SECRET_ROOM_ALT_ALT]           = {bpm = 0},
    --[Music.MUSIC_BOSS_OVER_TWISTED]             = {bpm = 0},
    ----[Music.MUSIC_CREDITS]                       = {bpm = 0},
    ----[Music.MUSIC_TITLE]                         = {bpm = 0},
    ----[Music.MUSIC_TITLE_AFTERBIRTH]              = {bpm = 0},
    ----[Music.MUSIC_TITLE_REPENTANCE]              = {bpm = 0},
    ----[Music.MUSIC_JINGLE_GAME_START_ALT]         = {bpm = 0},
    ----[Music.MUSIC_JINGLE_NIGHTMARE_ALT]          = {bpm = 0},
    ----[Music.MUSIC_MOTHERS_SHADOW_INTRO]          = {bpm = 0},
    ----[Music.MUSIC_DOGMA_INTRO]                   = {bpm = 0},
    ----[Music.MUSIC_STRANGE_DOOR_JINGLE]           = {bpm = 0},
    ----[Music.MUSIC_DARK_CLOSET]                   = {bpm = 0},
    ----[Music.MUSIC_CREDITS_ALT]                   = {bpm = 0},
    ----[Music.MUSIC_CREDITS_ALT_FINAL]             = {bpm = 0},
    ----[Music.MUSIC_JINGLE_BOSS]                   = {bpm = 0},
    ----[Music.MUSIC_JINGLE_BOSS_OVER]              = {bpm = 0},
    ----[Music.MUSIC_JINGLE_HOLYROOM_FIND]          = {bpm = 0},
    ----[Music.MUSIC_JINGLE_SECRETROOM_FIND]        = {bpm = 0},
    ----[Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_0]   = {bpm = 0},
    ----[Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_1]   = {bpm = 0},
    ----[Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_2]   = {bpm = 0},
    ----[Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_3]   = {bpm = 0},
    ----[Music.MUSIC_JINGLE_CHALLENGE_ENTRY]        = {bpm = 0},
    ----[Music.MUSIC_JINGLE_CHALLENGE_OUTRO]        = {bpm = 0},
    ----[Music.MUSIC_JINGLE_GAME_OVER]              = {bpm = 0},
    ----[Music.MUSIC_JINGLE_DEVILROOM_FIND]         = {bpm = 0},
    ----[Music.MUSIC_JINGLE_GAME_START]             = {bpm = 0},
    ----[Music.MUSIC_JINGLE_NIGHTMARE]              = {bpm = 0},
    ----[Music.MUSIC_JINGLE_BOSS_OVER2]             = {bpm = 0},
    ----[Music.MUSIC_JINGLE_HUSH_OVER]              = {bpm = 0},
    ----[Music.MUSIC_INTRO_VOICEOVER]               = {bpm = 0},
    ----[Music.MUSIC_EPILOGUE_VOICEOVER]            = {bpm = 0},
    --[Music.MUSIC_VOID]                          = {bpm = 0},
    --[Music.MUSIC_VOID_BOSS]                     = {bpm = 0},
    --[Music.MUSIC_DOWNPOUR]                      = {bpm = 0},
    --[Music.MUSIC_MINES]                         = {bpm = 0},
    --[Music.MUSIC_MAUSOLEUM]                     = {bpm = 0},
    --[Music.MUSIC_CORPSE]                        = {bpm = 0},
    --[Music.MUSIC_DROSS]                         = {bpm = 0},
    --[Music.MUSIC_ASHPIT]                        = {bpm = 0},
    --[Music.MUSIC_GEHENNA]                       = {bpm = 0},
    ----[Music.MUSIC_MORTIS]                        = {bpm = 0},
    --[Music.MUSIC_ISAACS_HOUSE]                  = {bpm = 0},
    ----[Music.MUSIC_FINAL_VOICEOVER]               = {bpm = 0},
    --[Music.MUSIC_DOWNPOUR_REVERSE]              = {bpm = 0},
    --[Music.MUSIC_DROSS_REVERSE]                 = {bpm = 0},
    ----[Music.MUSIC_MINESHAFT_AMBIENT]             = {bpm = 0},
    --[Music.MUSIC_MINESHAFT_ESCAPE]              = {bpm = 0},
    --[Music.MUSIC_REVERSE_GENESIS]               = {bpm = 0},
    ----[Music.MUSIC_DEATHMATCH]                    = {bpm = 0}
}

return tempoDefs