---@type table<Music, TempoDef>
local tempoDefs = {
    [Music.MUSIC_BASEMENT]                      = {name = "Diptera Sonata", bpm = 140},
    [Music.MUSIC_CAVES]                         = {name = "Sodden Hollow (Caves)", bpm = 120, bpms = {[3853] = 131.578, [4309] = 120}, offset = 83},
    [Music.MUSIC_DEPTHS]                        = {name = "Abyss (The Depths)", bpm = 95},
    [Music.MUSIC_CELLAR]                        = {name = "Periculum (The Cellar)", bpm = 140, offset = 64},
    [Music.MUSIC_CATACOMBS]                     = {name = "Capiticus Calvaria (Catacombs)", bpm = 120, offset = 50},
    [Music.MUSIC_NECROPOLIS]                    = {name = "When Blood Dries (Necropolis)", bpm = 120},
    [Music.MUSIC_WOMB_UTERO]                    = {name = "Viscera (Womb)", bpm = 90},
    [Music.MUSIC_GAME_OVER]                     = {name = "Acceptance (You Died)", bpm = 85, timeSig = 3},
    [Music.MUSIC_BOSS]                          = {name = "Crusade (Basic Boss Fight)", bpm = 150, timeSigs = {[2] = 4}},
    [Music.MUSIC_CATHEDRAL]                     = {name = "Everlasting Hymn (Cathedral)", bpm = 100},
    [Music.MUSIC_SHEOL]                         = {name = "Duress (Sheol)", bpm = 110, offset = 269},
    [Music.MUSIC_DARK_ROOM]                     = {name = "Devoid (Dark Room)", bpm = 90, offset = 82},
    [Music.MUSIC_CHEST]                         = {name = "Sketches of Pain (Chest Room)", bpm = 110, offset = 3},
    [Music.MUSIC_BURNING_BASEMENT]              = {name = "Fundamentum (Burning Basement)", bpm = 140, timeSigs = {[2] = 4}},
    [Music.MUSIC_FLOODED_CAVES]                 = {name = "Kave Diluvii (Flooded Caves)", bpm = 120, offset = 100},
    [Music.MUSIC_DANK_DEPTHS]                   = {name = "Pulso Profundum (Dank Depths)", bpm = 95},
    [Music.MUSIC_SCARRED_WOMB]                  = {name = "Cicatrix (Scarred Womb)", bpm = 90},
    [Music.MUSIC_BLUE_WOMB]                     = {name = "Nativitate (Dead Womb)", bpm = 80},
    [Music.MUSIC_UTERO]                         = {name = "Caesarian (Utero)", bpm = 90},
    [Music.MUSIC_MOM_BOSS]                      = {name = "Matricide (Mom Fight)", bpm = 160, timeSigs = {[3] = 4}},
    [Music.MUSIC_MOMS_HEART_BOSS]               = {name = "Ventricide (Womb Fight)", bpm = 160},
    [Music.MUSIC_ISAAC_BOSS]                    = {name = "Infanticide (Isaac Fight)", bpm = 120, offset = -253},
    [Music.MUSIC_SATAN_BOSS]                    = {name = "Hericide (Satan Fight)", bpm = 165, timeSigs = {[2] = 4}, offset = 31},
    [Music.MUSIC_DARKROOM_BOSS]                 = {name = "The Fallen Angel (Dark Room Fight)", bpm = 170, offset = 205},
    [Music.MUSIC_BLUEBABY_BOSS]                 = {name = "Ascension (Chest Fight)", bpm = 110, timeSigs = {[2] = 4}},
    [Music.MUSIC_BOSS2]                         = {name = "Cerebrum Dispersio (Boss Alt)", bpm = 150, offset = 26},
    [Music.MUSIC_HUSH_BOSS]                     = {name = "Morituros (Hush Fight)", bpm = 160, offset = 375},
    [Music.MUSIC_ULTRAGREED_BOSS]               = {name = "Chorus Mortis (Ultra Greed)", bpm = 165, offset = 109},
    [Music.MUSIC_LIBRARY_ROOM]                  = {name = "Tome of Knowledge (Library)", bpm = 110, bpms = {[3881] = 124.224, [4364] = 110}, offset = 57},
    [Music.MUSIC_SECRET_ROOM]                   = {name = "The Forgotten (Secret Room)", bpm = 120, timeSig = 3},
    [Music.MUSIC_SECRET_ROOM2]                  = {name = "Super Secret Room", bpm = 120, timeSig = 3},
    [Music.MUSIC_DEVIL_ROOM]                    = {name = "Anima Vendit (Deal With the Devil)"}, -- arrhythmic
    [Music.MUSIC_ANGEL_ROOM]                    = {name = "Empty Vessels (Angel Room)", bpm = 100},
    [Music.MUSIC_SHOP_ROOM]                     = {name = "Murmur of the Harvestman (Store)", bpm = 80, bpms = {[7580] = 89.418, [8250] = 80}, offset = 81},
    [Music.MUSIC_ARCADE_ROOM]                   = {name = "Genesis 13:37 (Retro Beats)", bpm = 130},
    [Music.MUSIC_BOSS_OVER]                     = {name = "The Calm", bpm = 85, timeSig = 3},
    [Music.MUSIC_CHALLENGE_FIGHT]               = {name = "Ambush", bpm = 150, offset = -93},
    [Music.MUSIC_BOSS_RUSH]                     = {name = "Armageddon (Boss Rush)", bpm = 180, timeSig = 7},
    [Music.MUSIC_JINGLE_BOSS_RUSH_OUTRO]        = {},
    [Music.MUSIC_BOSS3]                         = {name = "Juggernaut (Boss Alt)", bpm = 160},
    [Music.MUSIC_JINGLE_BOSS_OVER3]             = {},
    [Music.MUSIC_MOTHER_BOSS]                   = {name = "Morticide (Corpse Fight)", bpm = 130, triplet = true},
    [Music.MUSIC_DOGMA_BOSS]                    = {name = "Living in the Light", bpm = 180},
    [Music.MUSIC_BEAST_BOSS]                    = {name = "Revelations 13-1", bpm = 160, timeSig = 6},
    [Music.MUSIC_JINGLE_MOTHER_OVER]            = {},
    [Music.MUSIC_JINGLE_DOGMA_OVER]             = {},
    [Music.MUSIC_JINGLE_BEAST_OVER]             = {},
    [Music.MUSIC_PLANETARIUM]                   = {name = "Stargazer (Planetarium)", bpm = 120},
    [Music.MUSIC_SECRET_ROOM_ALT_ALT]           = {name = "Bygone", bpm = 120, offset = 49},
    [Music.MUSIC_BOSS_OVER_TWISTED]             = {name = "Dread (The Calm Twisted)", bpm = 85, timeSig = 3},
    [Music.MUSIC_CREDITS]                       = {name = "Tribute (Credits Roll)"},
    [Music.MUSIC_TITLE]                         = {name = "Genesis 22:10 (Title)"},
    [Music.MUSIC_TITLE_AFTERBIRTH]              = {name = "Regenesis (Title)"},
    [Music.MUSIC_TITLE_REPENTANCE]              = {name = "Genesis Retake Light"},
    [Music.MUSIC_JINGLE_GAME_START_ALT]         = {},
    [Music.MUSIC_JINGLE_NIGHTMARE_ALT]          = {},
    [Music.MUSIC_MOTHERS_SHADOW_INTRO]          = {},
    [Music.MUSIC_DOGMA_INTRO]                   = {},
    [Music.MUSIC_STRANGE_DOOR_JINGLE]           = {},
    [Music.MUSIC_DARK_CLOSET]                   = {},
    [Music.MUSIC_CREDITS_ALT]                   = {name = "Hush (Jesus Loves Uke)"},
    [Music.MUSIC_CREDITS_ALT_FINAL]             = {},
    [Music.MUSIC_JINGLE_BOSS]                   = {},
    [Music.MUSIC_JINGLE_BOSS_OVER]              = {},
    [Music.MUSIC_JINGLE_HOLYROOM_FIND]          = {},
    [Music.MUSIC_JINGLE_SECRETROOM_FIND]        = {},
    [Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_0]   = {},
    [Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_1]   = {},
    [Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_2]   = {},
    [Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_3]   = {},
    [Music.MUSIC_JINGLE_CHALLENGE_ENTRY]        = {},
    [Music.MUSIC_JINGLE_CHALLENGE_OUTRO]        = {},
    [Music.MUSIC_JINGLE_GAME_OVER]              = {},
    [Music.MUSIC_JINGLE_DEVILROOM_FIND]         = {},
    [Music.MUSIC_JINGLE_GAME_START]             = {},
    [Music.MUSIC_JINGLE_NIGHTMARE]              = {},
    [Music.MUSIC_JINGLE_BOSS_OVER2]             = {},
    [Music.MUSIC_JINGLE_HUSH_OVER]              = {},
    [Music.MUSIC_INTRO_VOICEOVER]               = {},
    [Music.MUSIC_EPILOGUE_VOICEOVER]            = {},
    [Music.MUSIC_VOID]                          = {name = "Terminus", bpm = 110},
    [Music.MUSIC_VOID_BOSS]                     = {name = "Delirium", bpm = 180, length = 106667, triplets = {[0] = false, [288] = true}},
    [Music.MUSIC_DOWNPOUR]                      = {name = "River of Despair (Downpour)", bpm = 144},
    [Music.MUSIC_MINES]                         = {name = "Fissure (Mines)", bpm = 136},
    [Music.MUSIC_MAUSOLEUM]                     = {name = "Walls of Denial (Mausoleum)", bpm = 119},
    [Music.MUSIC_CORPSE]                        = {name = "Carrion (Corpse)", bpm = 110, bpms = {[104181] = 128.755}, length = 104647},
    [Music.MUSIC_DROSS]                         = {name = "Night Soil (Dross)", bpm = 120, offset = 237},
    [Music.MUSIC_ASHPIT]                        = {name = "Absentia (Ashpit)", bpm = 106, timeSigs = {[3] = 4}},
    [Music.MUSIC_GEHENNA]                       = {name = "Morning Star (Gehenna)", bpm = 110},
    [Music.MUSIC_MORTIS]                        = {},
    [Music.MUSIC_ISAACS_HOUSE]                  = {name = "Home", bpm = 90, timeSig = 3},
    [Music.MUSIC_FINAL_VOICEOVER]               = {},
    [Music.MUSIC_DOWNPOUR_REVERSE]              = {bpm = 144},
    [Music.MUSIC_DROSS_REVERSE]                 = {bpm = 120},
    [Music.MUSIC_MINESHAFT_AMBIENT]             = {},
    [Music.MUSIC_MINESHAFT_ESCAPE]              = {bpm = 120},
    [Music.MUSIC_REVERSE_GENESIS]               = {bpm = 130, timeSig = 3}
}

local dm = Music.MUSIC_DEATHMATCH or Isaac.GetMusicIdByName("Deathmatch")
if dm then
    tempoDefs[dm]                               = {name = "There Can Be Only One"}
end

for _, def in pairs(tempoDefs) do
    def.artist = def.artist or "Rediculon"
end

return tempoDefs