---@class CollectibleCallbacks: Callbacks
---@field Priority_item? table<CallbackPriority, CollectibleCallbacks>
---@field PostAddCollectible_item? fun(type: CollectibleType, charge: integer, firstTime: boolean, slot: integer, varData: integer, player: EntityPlayer)
---@field PostTriggerCollectibleAdded_item? fun(player: EntityPlayer, type: CollectibleType, firstTime: boolean, wispOrInnate: boolean)
---@field PostTriggerCollectibleRemoved_item? fun(player: EntityPlayer, type: CollectibleType, removeFromPlayerForm: boolean, wispOrInnate: boolean)
---@field UseItem_item? fun(itemId: CollectibleType, rng: RNG, player: EntityPlayer, flags: integer, slot: ActiveSlot, custonVarData: integer): boolean?