---@class Callbacks
---
---@field PostNewRoom? fun()
---@field PostGameStarted? fun(continued: boolean)
---
---@field PostPlayerUpdate? fun(player: EntityPlayer)
---@field PostPlayerRender? fun(player: EntityPlayer)
---@field PreTriggerPlayerDeath? fun(player: EntityPlayer)
---@field EvaluateTearHitParams? fun(player: EntityPlayer, params: TearParams, weaponType: WeaponType, damageScale: number, tearDisplacement: integer, source: Entity)
---@field PostFireTear? fun(tear: EntityTear)
---@field PostFireBrimstone? fun(laser: EntityLaser)
---@field PostFireTechLaser? fun(laser: EntityLaser)
---@field PostFireTechXLaser? fun(laser: EntityLaser)
---@field PostFireKnife? fun(knife: EntityKnife)
---@field UseItem? fun(itemId: CollectibleType, rng: RNG, player: EntityPlayer, flags: integer, slot: ActiveSlot, custonVarData: integer): boolean?
---
---@field PreFamiliarUpdate? fun(familiar: EntityFamiliar): boolean?
---@field PostFamiliarUpdate? fun(familiar: EntityFamiliar)
---@field PostFamiliarFireTechLaser? fun(laser: EntityLaser)
---
---@field Tick? fun(measure?: boolean)
---
---@field EvaluateCache? table<CacheFlag, fun(player: EntityPlayer, flag: CacheFlag)>